make the error message clearer when running distroless containers
Previously you could generate a confusing warning like this:

```
$ docker run ghcr.io/astral-sh/uv run python
error: Could not read ELF interpreter from any of the following paths: /bin/sh, /usr/bin/env, /bin/dash, /bin/ls
```

Now the error message is better:

```
error: Failed to find a managed Python installation matching the current platform
  Caused by: Failed to determine the current platform
  Caused by: Failed to find any common binaries (/bin/sh, /usr/bin/env, /bin/dash, /bin/ls)
```

See https://github.com/astral-sh/uv/issues/8635.