Improve trace logs for debugging the error chain (#20220)
Our trace log that emits a debug representation of errors is useless for
`anyhow::Error` which is more common following
https://github.com/astral-sh/uv/pull/20188.

For `UvError::User`, we elide the trace log entirely, I do not expect us
to need to debug those error chains.

For `UvError::Unexpected`, we introduce a new
`uv_errors::debug_error_chain` formatter that walks each source and
renders its `Debug` representation. To retain parity with the previous
implementation, we also log the backtrace if available.

e.g.:

```diff
-TRACE Error trace: Failed to create virtual environment
-
-Caused by:
-    Not a directory (os error 20)
+TRACE Error chain:
+0: Creation(Io(Os { code: 20, kind: NotADirectory, message: "Not a directory" }))
+1: Io(Os { code: 20, kind: NotADirectory, message: "Not a directory" })
 error: Failed to create virtual environment
   Caused by: Not a directory (os error 20)
```