Bail when trying to attach ambiguous credentials instead of picking an arbitrary one (#16983)
This PR makes `TextCredentialStore.get_credentials` fail on ambiguous
matches, instead of returning the first "best" match while iterating
over all credentials.

Added a unit test, plus tested via:

```
❯ jq -n '{uri: "https://foo"}' | cargo -q run auth helper --protocol=bazel get
error: Multiple credentials found for URL 'https://foo/', specify which username to use
```
(the above needed two username/password combos registered for
`https://foo` using `uv auth login https://foo`)