Use absolute cache paths
Previously, git requirements would fail when settings `--cache-dir`:

```
cargo run --bin puffin -- pip-compile --cache-dir cache-all-kinds scripts/benchmarks/requirements/all-kinds.in
error: Failed to build distribution from URL: git+https://github.com/pydantic/pydantic-extra-types.git
  Caused by: Invalid path URL: cache-all-kinds/git-v0/db/b49ffcfeb6c2e9d8
  ```

The cause is that this is a relative and not an absolute path, which `Url` needs. This never showed up in the tests since the tests use absolute temp dirs for everything.