Don't panic for `uv init / --name foo`
No test since we don't know where the test runner will have access to `/` or not. I've manually confirmed that `uv init / --name foo` doesn't panic anymore.

The error message for it is mediocre but passable (same as e.g. `uv init /usr` on stable, no change just documenting it):

```
error: Failed to initialize Git repository at `/`
stdout:
stderr: /.git: Permission denied
```