Fix conflicting flag diagnostics for `--[no-]upgrade` and `--[no-]refresh` (#20839)
## Summary

These flags aren't global so we actually can't trigger the issue which
causes the warning to appear, but if we ever _did_ end up in a situation
where they trigger, we'd get this amazing result:

```
error: `--no-upgrade` and `--no-no-upgrade` cannot be used together. Boolean flags on different levels are currently not supported (https://github.com/clap-rs/clap/issues/6049)
```

;)

## Test Plan

Added a debug assert because humorous diagnostics are banned in uv.